export const persoImages: Array<PersoImageInterface> = [
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},

    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},

    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},

    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},

    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},

    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},

    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},

    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},
    {path: './assets/images/perso/appius_manilius.jpg', alt: 'appius manilius'},

  ];
  
  export interface PersoImageInterface {
    path: String,
    alt: String
  }
  